export const ADD_USER = "ADD_USER";
export const CREATED_PRODUCT = "CREATED_PRODUCT";
export const ADD_ALL_BEER = "ADD_ALL_BEER";
export const ORDER_FILTERS = "ORDER_FILTERS";
export const CREATED_COMPANY = "CREATED_COMPANY"
export const CREATED_USER = "CREATED_USER";
